version: '3.3'
volumes:
  mysql-db:
  mongo-db:

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: mongo
    stdin_open: true
    tty: true

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
    container_name: mysql
    stdin_open: true
    tty: true

  core:
    image: "risk-game_core:latest"
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: core
    stdin_open: true
    tty: true
    restart: "no"
    ports:
      # <Port exposed> : < Port running inside container>
      - '8080:8080'

  persistence:
    image: "risk-game_persistence:latest"
    build:
      context: ./persistence
      dockerfile: Dockerfile
    container_name: persistence
    stdin_open: true
    tty: true
    restart: "no"
    ports:
      # <Port exposed> : < Port running inside container>
      - '8081:8081'

  mapcreator:
    image: "risk-game_mapcreator:latest"
    build:
      context: ./mapcreator
      dockerfile: Dockerfile
    container_name: mapcreator
    stdin_open: true
    tty: true
    restart: "no"
    ports:
      # <Port exposed> : < Port running inside container>
      - '8082:8082'


